### ISSUE TITLE
Provide a way to access start context is hosted service

### ISSUE THREAD

**Issue by Nilavarasi-Ashika** [perpetualintelligence/terminal#101]
**Describe the bug**
Configure TerminalStartContext in dependency injection (DI) of the service instead can be handle in framework itself and provide a way to access start context is hosted service.

**Runtime**
OS: Linux
.NET 7.0.2
pi-cli v.5.1.1-rc

**Comment by Nilavarasi-Ashika** [comment]
@ameyasubhedarats @VijayakumarKothapalle @gilvargas FYI

**Comment by perpetualintelligencegit** [comment]
Added AddStartContext to register the TerminalStartContext  as a singleton it is available to both CommandRunner and any other service using DI.

```
        public static ITerminalBuilder AddStartContext(this ITerminalBuilder builder, TerminalStartContext terminalStartContext)
        {
            builder.Services.AddSingleton(terminalStartContext);
            return builder;
        }
```
