### ISSUE TITLE
Executing the commands loaded from assembly getting an issue

### ISSUE THREAD

**Issue by Nilavarasi-Ashika** [perpetualintelligence/terminal#114]
**Describe the bug**
Using LoadCommandSourceAsync() from ITerminalCommandSource<TContext> loading the commands from assembly dynamically.
Command execution getting the issue in command checker.  "The command checker is not registered with service collection"

**To Reproduce**
while debugging following code, 

logger.LogInformation("Load command runners. assembly={0}", assembly.GetName());
ServiceCollection localServiceCollection = new();
ITerminalBuilder terminalBuilder = localServiceCollection.CreateTerminalBuilder(textHandler);
terminalBuilder.AddDeclarativeAssembly(assembly);
ServiceProvider serviceProvider = localServiceCollection.BuildServiceProvider();
IEnumerable<CommandDescriptor> commands = serviceProvider.GetRequiredService<IEnumerable<CommandDescriptor>>();

observed "ITerminalBuilder terminalBuilder = localServiceCollection.CreateTerminalBuilder(textHandler);" 
This is creating a local instance so checker and runner are added here but this is never moved to global terminal builder that IHost creates and hence we are not able to find the checker.

**Comment by perpetualintelligencegit** [comment]
@Nilavarasi-Ashika : Thanks for reporting the issue. The immediate workaround is to add the command checker explicitly using AddTransient<> in your host initialization. This should unblock you. We are also working on the solution in the next path release.

**Comment by perpetualintelligencegit** [comment]
Fixed in v5.9.x. Introduced ICommandRuntime to resolve command runner and command checker for dynamic assemblies.

Need to add documentation examples.
