### ISSUE TITLE
Configure CommandType.Group in CommandDescriptor

### ISSUE THREAD

**Issue by Nilavarasi-Ashika** [perpetualintelligence/terminal#115]
**Describe the bug**
How to configure the group command in CommandDescriptor.
CommandDescriptor parameterized constructure supports following parameters in version pi-cli [5.8.5-rc.313242951].
(string id, string name, string description, CommandType commandType, CommandFlags commandFlags)

The expected command format syntax, how to configure this,
\<CommandOwner\> \<GroupName\> \<Command\> \<Option\> \<OptionValue\> 

**Runtime**
 - .NET 8.0
 - pi-cli [5.8.5-rc.313242951]

**Comment by perpetualintelligencegit** [comment]
@Nilavarasi-Ashika: The grouped commands are supported and working as expected. Please see our sample [test app](https://github.com/perpetualintelligence/terminal/tree/main/apps/OneImlx.Terminal.Apps.TestApp) for reference on how to correctly use grouped commands.

<img width="227" alt="image" src="https://github.com/perpetualintelligence/terminal/assets/91922269/3ab874de-7a47-493b-8485-7b5d199aa683">
