### ISSUE TITLE
Multiple Command Group supports same command syntax

### ISSUE THREAD

**Issue by Prabakaran-MS** [perpetualintelligence/terminal#122]
Multiple command group ability to support same command.

eg:
<commandOwner> <commandGroup> <command> <option>
1. cmdOwner group1 run --options
2. cmdOwner group2 run --options

**Comment by Nilavarasi-Ashika** [comment]
Please update the status of group command syntax.

**Comment by perpetualintelligencegit** [comment]
@Nilavarasi-Ashika Thanks for reporting the issue. We are investigating.

**Comment by Nilavarasi-Ashika** [comment]
Please share if any update?

**Comment by perpetualintelligencegit** [comment]
@Nilavarasi-Ashika : This is major change request since all the commands are expected to be unique and identified and executed by their descriptor identifier. `Id` property. At this moment this is a future enhancement request and we do not have a timeline for this request.

**Comment by Prabakaran-MS** [comment]
This is not a high-priority action item. Please keep this issue in the pipeline as a low priority.
