### ISSUE TITLE
Reset license keys causes to redeploy customer CLI terminals

### ISSUE THREAD

**Issue by prawasu** [perpetualintelligence/terminal#22]
**Describe the bug**
Our reset license keys regenerates the license keys and auth_apps both. The auth_apps are required in the `pi-cli` license configuration. 

This causes the customers to redeploy the terminals again.

**Expected behavior**
Authorized application identifiers should not be reset. This will allow the customers to update the license keys in the file without redeploying the terminals.

**Runtime**
 - OS: All OS
 - .NET e.g. 6.0.300
 - pi-cli 2.6.1-rc

**Comment by asperpint** [comment]
This is unexpected, the auth_apps should not reset. The regenerate API is resetting only the keys and unspecified claims. If the reset claims are not passed correctly that can cause this. Please make sure the auth_app is passed in claims so its not reset.

**Comment by perpetualintelligencegit** [comment]
We have introduced Application as a new features. The auth apps do not change till customer deletes them.
