### ISSUE TITLE
Prep for 5.x release

### ISSUE THREAD

**Issue by asperpint** [perpetualintelligence/terminal#46]
- [x] Close Bugs and Features
- [x] Customer communication
- [x] Documentation
- [x] Samples
- [x] Templates
- [x] Marketplace Update
- [x] Unit Tests

**Comment by perpetualintelligencegit** [comment]
Current planned production release is 5.9.x or 5.10.x
For Linux, Windows and MacOS
.NET 8 LTS.

**Comment by perpetualintelligencegit** [comment]
Tentative planned 5.10 release date 05/03/24

**Comment by Nilavarasi-Ashika** [comment]
Please Provide the release date for OneImlx.Terminal package production version of 5.11.

**Comment by perpetualintelligencegit** [comment]
Release already pushed to our CICID pipeline yesterday night. We should have the release package by end of today 05/09.

**Comment by ameyasubhedarats** [comment]
@Nilavarasi-Ashika : v5.11.1 released. Let us know if you face any issues or need any support.

**Comment by perpetualintelligencegit** [comment]
v5.11.1 Released.

**Comment by perpetualintelligencegit** [comment]
@Nilavarasi-Ashika please check.

**Comment by Nilavarasi-Ashika** [comment]
Thanks for support.
